---
kind: Deployment 
apiVersion: apps/v1 
metadata: 
  name: mongodb-express 
  labels:
    app: mongo-express 
spec: 
  replicas: 1
  selector:
    matchLabels: 
      app: mongo-express 
  template:
    metadata: 
      name: mongo-express 
      labels: 
        app: mongo-express 
    spec: 
      containers:
      - name: mongo-express
        image: mongo-express
        ports: 
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom: 
            # secret에 들어가 있음
            secretKeyRef:
              name: mongodb-secret
              # kubectl get secrets mongodb-secret -o yaml
              key: mongo-root-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom: 
            secretKeyRef: 
              name: mongodb-secret 
              key: mongo-root-password
        # Configmap쪽에 있음
        # kubectl get cm mongodb-configmap -o yaml
        - name: ME_CONFIG_MONGODB_URL
          valueFrom:
            configMapKeyRef: 
              name: mongodb-configmap 
              key: database_url
---
kind: Service 
apiVersion: v1 
metadata: 
  name: mongo-express-svc
  labels:
    app: mongo-express
spec:
  type: LoadBalancer
  # clusterIP: 10.100.10.10
  selector:
    app: mongo-express 
  ports:
  - port: 8081
    # containerport랑 맞춰주기
    targetPort: 8081
    nodePort: 30000

