---
kind: Pod 
apiVersion: v1 
metadata: 
  name: nginx-env-pod 
spec:
  containers:
  - name: nginx-container 
    images: nginx:1.14 
    ports:
    - containerPort: 80 
    env:
    - name: MYVAR
      value: "testvalue"

